<a href="https://colab.research.google.com/github/slavenbar/letterspython/blob/master2/DZ24Light_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import keras # Должны быть версии 2.2.5
import tensorflow as tf # Должна быть версия 1.15.0
import scipy # Должна быть 1.2.1
print('Keras: ',keras.__version__)
print('TensorFlow:', tf.__version__)
print('Scipy:' ,scipy.__version__)

# Если версия не совпадает - удаляем текущую и устанавливаем требуемую
#!pip uninstall keras
#!pip install keras==2.2.5

Using TensorFlow backend.


Keras:  2.2.5
TensorFlow: 1.15.0
Scipy: 1.1.0


In [ ]:
from flask import Flask # Импортируем модуль Flask 

In [ ]:
app = Flask(__name__) # Создаем экземпляр Flask (аргумнтом передается имя модуля или пакета)

In [ ]:
@app.route('/') # Декоратор, указывает, что URL будет вызывать нашу функцию
def hello(): # Задаем функцию для вывода сообщения
    return 'Hello, WORLD!!!'

In [ ]:
import threading # Импортируем модуль threading для запуска в отдельном потоке

In [ ]:
threading.Thread(target = app.run, kwargs = {'host' : 'localhost', 'port':5000}).start() # Запускаем в отдельном потоке метод app.run, который запускает локальный сервер

 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   Use a production WSGI server instead.


In [ ]:
import requests # Библиотека для HTTP-запросов

 * Debug mode: off


 * Running on http://localhost:5000/ (Press CTRL+C to quit)


In [ ]:
r = requests.get('http://localhost:5000') # Запрашиваем данные с локального сервера по порту 5000
print(r.status_code) # Статус ответа
print(r.encoding) # Кодировка после декодирования
print(r.apparent_encoding) # Текущая кодировка
print(r.text) # Соержимое страницы

127.0.0.1 - - [22/Sep/2020 21:44:46] "GET / HTTP/1.1" 200 -


200
utf-8
ascii
Hello, WORLD!!!


In [ ]:
!curl -X GET http://localhost:5000/

127.0.0.1 - - [22/Sep/2020 21:44:46] "GET / HTTP/1.1" 200 -


Hello, WORLD!!!


  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    15  100    15    0     0     68      0 --:--:-- --:--:-- --:--:--    69


In [ ]:
import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D
from keras import backend as K

In [ ]:
# Загружаем MNIST
from keras.datasets import mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()

x_train = x_train.reshape(x_train.shape[0], 28, 28, 1)
x_test = x_test.reshape(x_test.shape[0], 28, 28, 1)
input_shape = (28, 28, 1)

# Нормализуем значения пикспелей (от 0 до 1)
x_train = x_train.astype('float32')
x_test = x_test.astype('float32')
x_train /= 255
x_test /= 255

# Приводим лейблы к формату One Hot
y_train = keras.utils.to_categorical(y_train, 10)
y_test = keras.utils.to_categorical(y_test, 10)

print(x_train.shape, y_train.shape)

(60000, 28, 28, 1) (60000, 10)


In [ ]:
model = Sequential()
model.add(Conv2D(32, kernel_size=(3, 3),
                 activation='relu',
                 input_shape=input_shape))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(10, activation='softmax'))

model.compile(loss=keras.losses.categorical_crossentropy,
              optimizer=keras.optimizers.Adadelta(),
              metrics=['accuracy'])






Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.




In [ ]:
model.fit(x_train, y_train,
           batch_size=128,
           epochs=10,
           verbose=1,
           validation_data=(x_test, y_test))

# Результат модели
score = model.evaluate(x_test, y_test, verbose=0)
print('Test loss:', score[0])
print('Test accuracy:', score[1])


# Сохраняем саму модель
# Сериализация в JSON
model_json = model.to_json()
with open("model.json", "w") as json_file:
     json_file.write(model_json)
# Сохраняем(сериализуем) веса  в формате HDF5
model.save_weights("model.h5")
print("Сохранено")

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where



Train on 60000 samples, validate on 10000 samples
Epoch 1/10





60000/60000 [==============================] - 73s 1ms/step - loss: 0.2647 - acc: 0.9200 - val_loss: 0.0529 - val_acc: 0.9830
Epoch 2/10
60000/60000 [==============================] - 73s 1ms/step - loss: 0.0871 - acc: 0.9742 - val_loss: 0.0434 - val_acc: 0.9864
Epoch 3/10
60000/60000 [==============================] - 72s 1ms/step - loss: 0.0644 - acc: 0.9810 - val_loss: 0.0337 - val_acc: 0.9886
Epoch 4/10
60000/60000 [==============================] - 72s 1ms/step - loss: 0.0535 - acc: 0.9840 - val_loss: 0.0309 - val_acc: 0.9901
Epoch 5/10
60000/60000 [==============================] - 72s 1ms/step - loss: 0.0451 - acc: 0.9864 - val_loss: 0.0280 - val_acc: 0.9912
Epoch 6/10
60000/60000 [==============================] - 73s 1ms/step - loss: 0.0387 - acc: 0.9883 - val_loss: 0.0301 - val_acc: 0.9909
Epoch 7/10
60000/60000 [==

In [ ]:
from flask import Flask, request # request - это объекты, которыми управляет flask handles (get, set, post и т.д.)
from flask import render_template # этот объект автоматически зарендерит нам шаблон html
import imageio # для работы с изображениями
import numpy as np
import keras.models
import re # регулярные питоновские выражения
from keras.models import model_from_json
import sys 
import os
#from load import *

import tensorflow as tf
import base64 # универсальный формат кодирования (часто используется с изображениями)
from scipy.misc import imresize

In [ ]:
# Задаем имя серверу
app = Flask(__name__)

In [ ]:
# Открываем json файл разметки модели
json_file = open("model.json",'r') 
loaded_model_json = json_file.read() # считываем
json_file.close() # закрываем
loaded_model = model_from_json(loaded_model_json) # используем керас, чтобы считать разметку архитектуры
loaded_model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 26, 26, 32)        320       
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 24, 24, 64)        18496     
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 12, 12, 64)        0         
_________________________________________________________________
dropout_1 (Dropout)          (None, 12, 12, 64)        0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 9216)              0         
_________________________________________________________________
dense_1 (Dense)              (None, 128)               1179776   
_________________________________________________________________
dropout_2 (Dropout)          (None, 128)              

In [ ]:
loaded_model.load_weights("model.h5") # подгружаем веса
print("Загружено с диска")

Загружено с диска


In [ ]:
# компилируем модель
loaded_model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

# оценим ее точность еще раз
loss,accuracy = loaded_model.evaluate(x_test,y_test)
print('accuracy:', accuracy)

10000/10000 [==============================] - 3s 320us/step
accuracy: 0.9917


In [ ]:
# инициализируем граф
global graph
graph = tf.compat.v1.get_default_graph()

In [ ]:
# заносим его в дефолтный граф для сессии
session = tf.compat.v1.Session(graph=graph)  
init_g = tf.compat.v1.global_variables_initializer()

In [ ]:
def convertImage(imgData):
    imgstr = re.search(b'base64,(.*)', imgData).group(1)
    with open('output.png', 'wb') as output:
        output.write(base64.decodebytes(imgstr))

In [ ]:
## # Указываем адрес по которому будет откликаться Web сервис и задаем саму функцию веб сервиса. Это наша стартовая страница
@app.route('/')
@app.route('/index')
def index():
    return render_template("index.html")

In [ ]:
# маршрут, по которому будет идти предсказание
@app.route('/predict/',methods=['GET','POST'])
def predict():
    # в любой момент, когда пользователь вызовет predict
    # после того, как нарисовал картинку, произойдет
    # inference/внедрение, вернется результат классификации
    
    # получить сырой формат изображения (этот метод объекта Flask)
    imgData = request.get_data()
    
    # кодируем в подходящий формат
    convertImage(imgData)
    print ("debug")
    # считываем изображение в память
    x = imageio.imread('output.png',pilmode='L')
    # побитово инвертируем (из черного в белое и наоборот)
    x = np.invert(x)
    # выравниваем по размеру
    x = imresize(x,(28,28))
    # преобразуем в четырехразмерный тензор для модели
    x = x.reshape(1,28,28,1)
    print ("debug2")
    
    # инициализируем все переменные для графа
    session.run(init_g)
    #tf.compat.v1.global_variables_initializer()

   # session = tf.Session(graph=graph)
    
    # в сессии, заданной по умолчанию
    #with session.as_default():
        # в графе, заданном по умолчанию
    with graph.as_default():
           
            out = loaded_model.predict(x)            
            print(out[0])
            print(np.argmax(out,axis=1))
            print ("debug3")
            
        # преобразуем ответ в строку
            response = np.array_str(np.argmax(out,axis=1))
            return response
        # обнуляем граф, чтобы можно было ввести новые данные
    tf.reset_default_graph()

In [ ]:
if __name__ == "__main__":
    # этот порт выделяем под прогонку
    port = int(os.environ.get('PORT', 5002))
    
    # прогоняем на локальном сервере по заданному порту
    app.run(host='127.0.0.1', port=port,debug=False)
    
    # опционально, если хотите прогнать в режиме дебага
    #app.run(debug=True)

 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   Use a production WSGI server instead.
 * Debug mode: off


 * Running on http://127.0.0.1:5002/ (Press CTRL+C to quit)
127.0.0.1 - - [22/Sep/2020 21:57:06] "GET / HTTP/1.1" 200 -


debug
debug2


C:\Users\Gazukin\anaconda3\envs\newfuck\lib\site-packages\ipykernel_launcher.py:19: DeprecationWarning:     `imresize` is deprecated!
    `imresize` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
    Use ``skimage.transform.resize`` instead.
127.0.0.1 - - [22/Sep/2020 21:57:09] "POST /predict/ HTTP/1.1" 200 -


[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
[1]
debug3


127.0.0.1 - - [22/Sep/2020 21:57:15] "POST /predict/ HTTP/1.1" 200 -


debug
debug2
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
[2]
debug3


127.0.0.1 - - [22/Sep/2020 21:57:30] "POST /predict/ HTTP/1.1" 200 -


debug
debug2
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
[5]
debug3


In [ ]:
ONNX

In [ ]:
import numpy as np
from keras.preprocessing import image
import os
os.environ['TF_KERAS'] = '1'
import onnx
import keras2onnx
import onnxruntime 
from tensorflow.keras.preprocessing.image import img_to_array, load_img
from tensorflow.keras.models import model_from_json
import matplotlib.pyplot as plt

In [ ]:
# предобработка изображения  
x = img_to_array(load_img('output.png', target_size=(28,28), color_mode='grayscale')).astype('float32')[:,:,0]
x /= 255
x = 1 - x
x = x.reshape(1,28,28,1)

# загрузим предобученную сеть
json_file = open('model.json','r') 
loaded_model_json = json_file.read() # считываем
json_file.close() # закрываем
loaded_model = model_from_json(loaded_model_json)
loaded_model.load_weights("model.h5") # подгружаем веса

In [ ]:
# конвертируем в onnx
onnx_model = keras2onnx.convert_keras(loaded_model, loaded_model.name)

In [ ]:
# предсказание от onnxruntime
content = onnx_model.SerializeToString() # сериализуем
sess = onnxruntime.InferenceSession(content) # инференс этого представления в сессию

x = x if isinstance(x, list) else [x] # если принадлежит классу список

print(len(x))
print(x[0].shape)

feed = dict([(inputs.name, x[n]) for n, inputs in enumerate(sess.get_inputs())]) # sess.get_inputs() - получить описание того, что будет подаваться на вход


In [ ]:
outputs = sess.get_outputs()[0].name
pred_onnx = np.array(sess.run([outputs], feed)).argmax()

In [ ]:
print(np.array(pred_onnx).shape)

In [ ]:
%matplotlib inline
img = img_to_array(load_img('output.png', target_size=(28,28), color_mode='grayscale')).astype('float32')[:,:,0]
img /= 255
plt.imshow(img, cmap = 'gray')
plt.show()

print('Результат распознования: ', pred_onnx)